"""WP-F golden parity + manifest gates for the SB3 SAC live adapter.

The golden fixture (tests/data/sac_golden_parity_eth_v2.json) was
generated by agent-multi/tools/generate_sac_golden_parity.py: the
TRAINING stack rolled the artifact deterministically through the gym-fx
environment and recorded every (observation, raw action, mapping)
triple. The lts adapter must reproduce the raw actions bit-exactly and
the same long/short/hold mapping — otherwise it must never hold venue
authority.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np
import pytest

from app.live_sac_selection import (
    LiveSacPolicy,
    LiveSacSelectionError,
    SelectedSacPolicy,
)

FIXTURE = Path(__file__).parent / "data/sac_golden_parity_eth_v2.json"


def _load_fixture():
    if not FIXTURE.exists():
        pytest.skip("golden parity fixture not generated on this host")
    fixture = json.loads(FIXTURE.read_text())
    artifact = Path(fixture["artifact_file"])
    if not artifact.exists():
        pytest.skip("golden parity artifact not present on this host")
    return fixture


def _observation(record):
    part = record["observation"]["__array__"]
    return np.asarray(
        part["values"], dtype=np.float32).reshape(part["shape"])


@pytest.fixture(scope="module")
def golden():
    fixture = _load_fixture()
    policy = LiveSacPolicy.load(
        fixture["artifact_file"], fixture["artifact_sha256"],
        model_id="parity-fixture", asset_id="ETHUSD", timeframe="4h",
        continuous_action_threshold=fixture[
            "continuous_action_threshold"],
    )
    return fixture, policy


def test_golden_action_parity(golden):
    fixture, policy = golden
    mismatches = []
    for index, record in enumerate(fixture["records"]):
        observation = _observation(record)
        assert hashlib.sha256(observation.tobytes()).hexdigest() == \
            record["observation_sha256"], f"fixture corrupt at {index}"
        result = policy.predict(observation)
        if result["raw_action"] != record["raw_action"]:
            mismatches.append(
                (index, result["raw_action"], record["raw_action"]))
        assert result["action"] == record["mapped_action"], index
    assert not mismatches, f"raw action drift: {mismatches[:5]}"


def test_artifact_hash_mismatch_refused(golden):
    fixture, _policy = golden
    with pytest.raises(LiveSacSelectionError, match="hash mismatch"):
        LiveSacPolicy.load(
            fixture["artifact_file"], "0" * 64,
            model_id="parity-fixture", asset_id="ETHUSD",
            timeframe="4h", continuous_action_threshold=0.1)


def test_threshold_mapping_matches_gym_fx_coerce_action(golden):
    """The adapter's mapping must be inclusive at +/- threshold exactly
    like gym-fx `_coerce_action` (>= thr long, <= -thr short)."""
    _fixture, policy = golden
    thr = policy.continuous_action_threshold
    space = policy.observation_space.shape

    class _Stub:
        observation_space = policy.observation_space

        def predict(self, obs, deterministic):
            return np.array([self.value], dtype=np.float32), None

    stub = _Stub()
    probe = LiveSacPolicy(
        model=stub, model_id="stub", asset_id="ETHUSD", timeframe="4h",
        artifact_sha256="0" * 64, continuous_action_threshold=thr)
    observation = np.zeros(space, dtype=np.float32)
    for value, expected in (
        (thr, "long"), (thr + 0.01, "long"),
        (-thr, "short"), (-thr - 0.01, "short"),
        (thr - 1e-4, "hold"), (-thr + 1e-4, "hold"), (0.0, "hold"),
    ):
        stub.value = value
        assert probe.predict(observation)["action"] == expected, value


def test_observation_shape_and_finiteness_guards(golden):
    _fixture, policy = golden
    with pytest.raises(LiveSacSelectionError, match="shape"):
        policy.predict(np.zeros(3, dtype=np.float32))
    bad = np.zeros(policy.observation_space.shape, dtype=np.float32)
    bad[0] = np.nan
    with pytest.raises(LiveSacSelectionError, match="non-finite"):
        policy.predict(bad)


def test_v2_target_exposure_contract_emits_explicit_close(golden):
    _fixture, policy = golden

    class _Stub:
        observation_space = policy.observation_space
        value = 0.0

        def predict(self, obs, deterministic):
            return np.array([self.value], dtype=np.float32), None

    stub = _Stub()
    probe = LiveSacPolicy(
        model=stub, model_id="v2-stub", asset_id="ETHUSD", timeframe="4h",
        artifact_sha256="0" * 64, continuous_action_threshold=0.2,
        continuous_action_contract="target_exposure_hysteresis_v2",
        continuous_exit_threshold=0.05,
    )
    observation = np.zeros(policy.observation_space.shape, dtype=np.float32)

    assert probe.predict(observation, current_exposure=1.0)["action"] == "close"
    assert probe.predict(observation, current_exposure=-1.0)["action"] == "close"
    assert probe.predict(observation, pending_entry=True)["action"] == "close"
    assert probe.predict(observation)["action"] == "hold"
    stub.value = 0.1
    assert probe.predict(observation, current_exposure=1.0)["action"] == "hold"


def _manifest(tmp_path, fixture, **overrides):
    config_file = tmp_path / "config.json"
    config_file.write_text("{}")
    manifest = {
        "schema": "prediction_provider.live_sac_manifest.v1",
        "model_id": "parity-fixture",
        "asset_id": "ETHUSD",
        "timeframe": "4h",
        "artifact_file": fixture["artifact_file"],
        "artifact_sha256": fixture["artifact_sha256"],
        "config_file": str(config_file),
        "config_sha256": hashlib.sha256(b"{}").hexdigest(),
        "research_validated": True,
        "live_inference_eligible": False,
        "live_execution_eligible": False,
        "observation_parity_verified": True,
        "observation_contract": {
            "source": "gym_fx_feature_window",
            "continuous_action_threshold": fixture[
                "continuous_action_threshold"],
        },
    }
    manifest.update(overrides)
    path = tmp_path / "manifest.json"
    path.write_text(json.dumps(manifest))
    return path


def test_manifest_demo_tier_loads(tmp_path):
    fixture = _load_fixture()
    selected = SelectedSacPolicy(
        manifest_file=_manifest(tmp_path, fixture),
        expected_asset_id="ETHUSD", expected_timeframe="4h",
        execution_tier="demo_research_canary")
    assert selected.policy.artifact_sha256 == fixture["artifact_sha256"]


def test_manifest_paper_tier_requires_promotion(tmp_path):
    fixture = _load_fixture()
    with pytest.raises(LiveSacSelectionError, match="not promoted"):
        SelectedSacPolicy(
            manifest_file=_manifest(tmp_path, fixture),
            expected_asset_id="ETHUSD", expected_timeframe="4h",
            execution_tier="promoted_paper")


def test_manifest_requires_parity_evidence(tmp_path):
    fixture = _load_fixture()
    with pytest.raises(LiveSacSelectionError, match="parity"):
        SelectedSacPolicy(
            manifest_file=_manifest(
                tmp_path, fixture, observation_parity_verified=False),
            expected_asset_id="ETHUSD", expected_timeframe="4h",
            execution_tier="demo_research_canary")


def test_manifest_route_mismatch_refused(tmp_path):
    fixture = _load_fixture()
    with pytest.raises(LiveSacSelectionError, match="asset"):
        SelectedSacPolicy(
            manifest_file=_manifest(tmp_path, fixture),
            expected_asset_id="USDCAD", expected_timeframe="4h",
            execution_tier="demo_research_canary")
